"use client";
import {useEffect,useState} from 'react';
export function ScoutBudgetPanel() {
 const [data,setData]=useState<any>(null);const [message,setMessage]=useState('');
 async function load(){try{const res=await fetch('/api/sport-hub/scout/budget');const value=await res.json();if(!res.ok)throw new Error(value.error);setData(value);}catch(e:any){setMessage(e.message);}}
 useEffect(()=>{void load();},[]);
 async function save(e:React.FormEvent){e.preventDefault();const res=await fetch('/api/sport-hub/scout/budget',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({sessionUsd:data.settings.session_usd,dailyUsd:data.settings.daily_usd,verificationUsd:data.settings.verification_usd,enabled:data.settings.enabled})});const value=await res.json();setMessage(res.ok?'Budget settings saved.':value.error);if(res.ok)await load();}
 return <section className="rounded-xl border bg-white p-4 space-y-3"><h2 className="font-bold">Apify Budget & Usage (USD)</h2>{message && <p role="status">{message}</p>}{data && <><form onSubmit={save} className="flex flex-wrap gap-3">{[['session_usd','Session limit'],['daily_usd','Daily limit'],['verification_usd','Verification limit']].map(([key,label])=><label key={key} className="text-sm">{label}<input type="number" min="0.01" step="0.01" required value={data.settings[key]} onChange={e=>setData({...data,settings:{...data.settings,[key]:Number(e.target.value)}})} className="block border rounded p-2" /></label>)}<label><input type="checkbox" checked={data.settings.enabled} onChange={e=>setData({...data,settings:{...data.settings,enabled:e.target.checked}})} /> Enable paid scouting</label><button className="rounded bg-slate-900 text-white px-3 py-2">Save Budget</button></form><p className="text-xs">Run limits: ${Number(data.settings.run_usd).toFixed(2)} default · ${Number(data.settings.tiktok_run_usd).toFixed(2)} TikTok. Day boundary: Asia/Ho_Chi_Minh. Unknown charges retain their reservation.</p><div className="overflow-auto"><table className="text-xs w-full"><thead><tr>{['Platform','Task','Actor','State','Charge / Held USD'].map(t=><th key={t}>{t}</th>)}</tr></thead><tbody>{data.runs.map((r:any,i:number)=><tr key={i}><td>{r.platform}</td><td>{r.task}</td><td>{r.actor}</td><td>{r.state}</td><td>{r.actual_usd==null?`Held $${Number(r.reserved_usd).toFixed(2)}`:`$${Number(r.actual_usd).toFixed(4)}`}</td></tr>)}</tbody></table></div><h3 className="font-semibold text-sm">Cost per Saved Outcome (USD)</h3><p className="text-xs">Latest {data.runs.length.toLocaleString('en-US')} runs. Missing billing or no saved outcomes show Unknown.</p><div className="overflow-auto"><table className="text-xs w-full"><thead><tr>{['Module','Accepted Candidate','New Post','Comment Used in Audit'].map(label=><th key={label}>{label}</th>)}</tr></thead><tbody>{data.summaries.map((s:any)=><tr key={s.sessionId}><td>{s.module}</td>{['costPerAcceptedCandidate','costPerNewPost','costPerCommentUsedInAudit'].map(key=><td key={key}>{s[key]==null?'Unknown':`$${Number(s[key]).toFixed(4)}`}</td>)}</tr>)}</tbody></table></div></>}</section>;
}
