import {beforeEach,describe,expect,it,vi} from 'vitest';
const state=vi.hoisted(()=>({tables:{} as Record<string,any[]>,claims:0,settlements:[] as any[]}));
vi.mock('@/lib/supabase/admin',()=>({createAdminClient:()=>({from(table:string){let op='select';let value:any;const filters:((r:any)=>boolean)[]=[];
 const result=()=>{const rows=state.tables[table] ||= [];const matching=rows.filter(r=>filters.every(f=>f(r)));if(op==='update'){matching.forEach(r=>Object.assign(r,value));return {data:matching,error:null};}if(op==='upsert'){const match=rows.find(r=>r.cache_key===value.cache_key);if(match)Object.assign(match,value);else rows.push(value);return {data:value,error:null};}return {data:matching,error:null};};
 const q:any={not:(k:string,_op:string,v:any)=>{filters.push(r=>r[k]!=v);return q;},is:(k:string,v:any)=>{filters.push(r=>r[k]==v);return q;},in:(k:string,v:any[])=>{filters.push(r=>v.includes(r[k]));return q;},order:()=>q,limit:()=>q,or:(condition:string)=>{const key=condition.split('.')[0];filters.push(r=>!r[key] || Date.parse(r[key])<Date.now());return q;},select:()=>q,eq:(k:string,v:any)=>{filters.push(r=>(['params','input'].includes(k) && typeof v==='string' ? JSON.stringify(r[k])===v : r[k]===v));return q;},gt:(k:string,v:any)=>{filters.push(r=>r[k]>v);return q;},update:(v:any)=>{op='update';value=v;return q;},upsert:(v:any)=>{op='upsert';value=v;return q;},single:async()=>{const r=result();return {...r,data:r.data[0]};},maybeSingle:async()=>{const r=result();return {...r,data:r.data[0] || null};},then:(resolve:any)=>Promise.resolve(result()).then(resolve)};return q;},async rpc(name:string,p:any){if(name==='reserve_scout_run'){const rows=state.tables.scout_provider_runs;const old=rows.find(r=>r.task_key===p.p_key && r.session_id===p.p_session);if(old)return {data:{claimed:false,run:old},error:null};state.claims++;const run={id:'reservation-'+state.claims,session_id:p.p_session,task_key:p.p_key,state:'reserved',reserved_usd:.25};rows.push(run);return {data:{claimed:true,run},error:null};}state.settlements.push(p);const run=state.tables.scout_provider_runs.find(r=>r.id===p.p_run);if(run)run.state=p.p_state;return {data:null,error:null};}})}));
import {executePlan,inputKey,capabilityKey,knownCharge,validateProviderItem,reconcileProviderBilling} from './runtime';
import {reconcileUnconfirmedStarts} from './start-reconciliation';
const plan={actor:'apify~instagram-scraper',input:{search:'run',resultsType:'details'}};
beforeEach(()=>{vi.restoreAllMocks();process.env.APIFY_TOKEN='test';state.claims=0;state.settlements=[];state.tables={scout_sessions:[{id:'s',params:{},runtime_version:2}],scout_provider_runs:[],scout_provider_cache:[],scout_provider_capabilities:[{capability_key:capabilityKey(plan,'profiles'),verified:true,build:'1.2.3'}]};});
function provider(status='SUCCEEDED',rows:any[]=[{username:'runner',followersCount:0}]){const fetch=vi.fn(async(url:any)=>new Response(JSON.stringify(String(url).includes('/acts/')?{data:{id:'r',defaultDatasetId:'d',buildId:'b'}}:String(url).includes('/actor-runs/')?{data:{status,finishedAt:'2026-10-05T00:00:00Z',buildId:'b',storageIds:{datasets:{default:'d'}}}}:rows)));vi.stubGlobal('fetch',fetch);return fetch;}
describe('Paid-run invariants',()=>{
 it('hashes complete input independent of object key order',()=>{expect(inputKey('a','1','t',{b:2,a:1})).toBe(inputKey('a','1','t',{a:1,b:2}));expect(inputKey('a','1','t',{searchType:'pages'})).not.toBe(inputKey('a','1','t',{searchType:'profiles'}));});
 it('refuses unverified capabilities before reservation or start',async()=>{state.tables.scout_provider_capabilities=[];const fetch=provider();await expect(executePlan('s','Instagram','profiles',plan)).rejects.toMatchObject({code:'CAPABILITY_UNVERIFIED'});expect(state.claims).toBe(0);expect(fetch).not.toHaveBeenCalled();});
 it('uses capped run options, provenance, and reads completed data only once',async()=>{const fetch=provider();const first=await executePlan('s','Instagram','profiles',plan);expect(first[0]).toMatchObject({followersCount:0,_provenance:{runId:'r',buildId:'b'}});await executePlan('s','Instagram','profiles',plan);expect(fetch).toHaveBeenCalledTimes(3);expect(String(fetch.mock.calls[0][0])).toContain('maxTotalChargeUsd=0.25');});
 it('retains pending run identity across polling',async()=>{const fetch=provider('RUNNING');await expect(executePlan('s','Instagram','profiles',plan)).rejects.toMatchObject({code:'PENDING'});await expect(executePlan('s','Instagram','profiles',plan)).rejects.toMatchObject({code:'PENDING'});expect(fetch.mock.calls.filter(c=>String(c[0]).includes('/acts/'))).toHaveLength(1);expect(fetch.mock.calls.filter(c=>String(c[0]).includes('/datasets/'))).toHaveLength(0);});
 it('reuses the pending run even if the configured build changes',async()=>{const fetch=provider('RUNNING');await expect(executePlan('s','Instagram','profiles',plan)).rejects.toMatchObject({code:'PENDING'});state.tables.scout_provider_capabilities[0].build='1.2.4';await expect(executePlan('s','Instagram','profiles',plan)).rejects.toMatchObject({code:'PENDING'});expect(state.claims).toBe(1);expect(fetch.mock.calls.filter(c=>String(c[0]).includes('/acts/'))).toHaveLength(1);});
 it('does not repeat an ambiguous start',async()=>{const fetch=vi.fn(async()=>{throw new TypeError('connection lost');});vi.stubGlobal('fetch',fetch);await expect(executePlan('s','Instagram','profiles',plan)).rejects.toMatchObject({code:'START_UNKNOWN'});await expect(executePlan('s','Instagram','profiles',plan)).rejects.toMatchObject({code:'START_UNKNOWN'});expect(fetch).toHaveBeenCalledTimes(1);expect(state.settlements).toHaveLength(0);});
 it('keeps a known run identity even when its initial response omits the dataset',async()=>{
  const fetch=vi.fn(async(url:any)=>new Response(JSON.stringify(String(url).includes('/acts/')?{data:{id:'r',buildId:'b'}}:String(url).includes('/actor-runs/')?{data:{status:'SUCCEEDED',defaultDatasetId:'d',usageTotalUsd:0}}:[{username:'runner'}])));vi.stubGlobal('fetch',fetch);
  expect(await executePlan('s','Instagram','profiles',plan)).toHaveLength(1);expect(state.tables.scout_provider_runs[0].provider_run_id).toBe('r');expect(fetch.mock.calls.some(c=>String(c[0]).includes('/datasets/d/'))).toBe(true);
 });
 it('blocks a new session from bypassing an unresolved paid start',async()=>{
  const hash=inputKey(plan.actor,'1.2.3','profiles',plan.input);state.tables.scout_provider_runs=[{id:'unknown',session_id:'old',actor:plan.actor,input:plan.input,cache_key:hash,state:'start-unknown',provider_run_id:null}];const fetch=provider();
  await expect(executePlan('s','Instagram','profiles',plan)).rejects.toMatchObject({code:'START_UNKNOWN'});expect(fetch).not.toHaveBeenCalled();expect(state.claims).toBe(0);
 });
 it('shares fresh raw evidence across sessions without starting a run',async()=>{const fetch=provider();await executePlan('s','Instagram','profiles',plan);state.tables.scout_sessions.push({id:'s2',params:{},runtime_version:2});const rows=await executePlan('s2','Instagram','profiles',plan);expect(rows[0]._provenance.cached).toBe(true);expect(state.claims).toBe(1);expect(fetch).toHaveBeenCalledTimes(3);});
 it('keeps valid items and records partial errors',async()=>{provider('SUCCEEDED',[{username:'runner'},{error:'private'}]);const rows=await executePlan('s','Instagram','profiles',plan);expect(rows).toHaveLength(1);expect(rows[0]._provenance.warnings).toEqual(['Instagram: One item was skipped because the provider reports that it is private. Other available results are retained for review.']);expect(state.tables.scout_provider_runs[0].warnings).toHaveLength(1);expect(state.tables.scout_provider_cache).toHaveLength(0);});
 it('preserves known rate rejection without calling start again',async()=>{const fetch=vi.fn(async()=>new Response(JSON.stringify({error:{type:'rate-limit'}}),{status:429}));vi.stubGlobal('fetch',fetch);await expect(executePlan('s','Instagram','profiles',plan)).rejects.toMatchObject({code:'RATE_LIMITED'});await expect(executePlan('s','Instagram','profiles',plan)).rejects.toMatchObject({code:'RATE_LIMITED'});expect(fetch).toHaveBeenCalledTimes(1);expect(state.settlements[0].p_amount).toBe(0);});
 it('settles a known run after its session has ended without starting or downloading another run',async()=>{state.tables.scout_provider_runs=[{id:'reservation',provider_run_id:'r',state:'running',actual_usd:null}];const fetch=vi.fn(async(_url:any)=>new Response(JSON.stringify({data:{status:'SUCCEEDED',usageTotalUsd:.03}})));vi.stubGlobal('fetch',fetch);await reconcileProviderBilling();expect(state.settlements).toHaveLength(1);expect(state.settlements[0]).toMatchObject({p_run:'reservation',p_amount:.03});expect(fetch).toHaveBeenCalledTimes(1);expect(String(fetch.mock.calls[0][0])).toContain('/actor-runs/r');});
 it('never treats unknown pricing as zero',()=>{expect(knownCharge({})).toBeNull();expect(knownCharge({usageTotalUsd:0})).toBe(0);expect(knownCharge({chargedTotalUsd:.03})).toBe(.03);});
 it('rejects invalid metrics without inventing replacements',()=>{expect(validateProviderItem(plan.actor,'profiles',{username:'a',followersCount:'lots'})).toBe(false);});
});
describe('unconfirmed-start reconciliation',()=>{
 function unknown(age=10*60000){state.tables.scout_sessions=[{id:'s',owner_id:'o',result:{code:'START_UNKNOWN'}}];state.tables.scout_provider_runs=[{id:'unknown',session_id:'s',actor:plan.actor,created_at:new Date(Date.now()-age).toISOString(),state:'start-unknown',provider_run_id:null}];}
 function history(items:any[],total=items.length){const fetch=vi.fn(async()=>new Response(JSON.stringify({data:{offset:0,desc:true,count:items.length,total,items}})));vi.stubGlobal('fetch',fetch);return fetch;}
 it('releases a stale reservation only after a complete provider time window rules out any start',async()=>{unknown();const fetch=history([{id:'old',startedAt:new Date(Date.now()-3600000).toISOString()}]);expect(await reconcileUnconfirmedStarts('s','o')).toMatchObject({reconciled:true});expect(state.settlements[0]).toMatchObject({p_state:'rejected:START_NOT_CREATED',p_amount:0});expect(state.tables.scout_sessions[0].result.code).toBe('START_NOT_CREATED');expect(fetch.mock.calls.every(([,options]:any)=>!options || options.method==='GET')).toBe(true);});
 it('holds a reservation if any provider run exists in its start window',async()=>{unknown();history([{id:'possible',startedAt:new Date(Date.now()-9*60000).toISOString()}]);expect(await reconcileUnconfirmedStarts('s','o')).toMatchObject({reconciled:false});expect(state.settlements).toHaveLength(0);});
 it('does not infer absence from incomplete pagination',async()=>{unknown();history([],10);expect(await reconcileUnconfirmedStarts('s','o')).toMatchObject({reconciled:false});expect(state.settlements).toHaveLength(0);});
 it('does not reconcile a young start or expired history',async()=>{for(const age of [60000,25*3600000]){unknown(age);const fetch=history([]);expect(await reconcileUnconfirmedStarts('s','o')).toMatchObject({reconciled:false});expect(fetch).not.toHaveBeenCalled();}expect(state.settlements).toHaveLength(0);});
 it('enforces ownership before reading provider history',async()=>{unknown();const fetch=history([]);await expect(reconcileUnconfirmedStarts('s','someone-else')).rejects.toMatchObject({code:'NOT_FOUND'});expect(fetch).not.toHaveBeenCalled();});
 it('preserves the hold if provider history is unavailable',async()=>{unknown();vi.stubGlobal('fetch',vi.fn(async()=>{throw new TypeError('offline');}));await expect(reconcileUnconfirmedStarts('s','o')).rejects.toMatchObject({code:'PROVIDER_UNAVAILABLE'});expect(state.settlements).toHaveLength(0);});
 it('unblocks a retry with no own runs after the original reservation is resolved',async()=>{state.tables.scout_sessions=[{id:'s',owner_id:'o',kind:'preview',params:{keyword:'running',platform:['Instagram']},result:{code:'START_UNKNOWN'}}];state.tables.scout_provider_runs=[];const fetch=history([]);expect(await reconcileUnconfirmedStarts('s','o')).toMatchObject({reconciled:true});expect(fetch).not.toHaveBeenCalled();expect(state.settlements).toHaveLength(0);});
 it('keeps a blocked retry paused while the original unresolved reservation exists',async()=>{state.tables.scout_sessions=[{id:'s',owner_id:'o',kind:'preview',params:{keyword:'running',platform:['Instagram']},result:{code:'START_UNKNOWN'}}];state.tables.scout_provider_runs=[{id:'original',session_id:'old',platform:'Instagram',input:{search:'running'},state:'start-unknown',provider_run_id:null}];expect(await reconcileUnconfirmedStarts('s','o')).toMatchObject({reconciled:false});expect(state.settlements).toHaveLength(0);});
});

describe('Facebook audience contract validation',()=>{
 it('accepts a details page URL with observed followers and rejects malformed counts',()=>{
  expect(validateProviderItem('apify~facebook-pages-scraper','profile-details',{pageUrl:'https://facebook.com/nike',followers:39000000})).toBe(true);
  expect(validateProviderItem('apify~facebook-pages-scraper','profile-details',{pageUrl:'https://facebook.com/nike',followers:'many'})).toBe(false);
  expect(validateProviderItem('apify~facebook-pages-scraper','profile-details',{pageUrl:'https://facebook.com/nike',followers:0})).toBe(true);
 });
});
