import {beforeEach,describe,expect,it,vi} from 'vitest';
const state=vi.hoisted(()=>({tables:{} as Record<string,any[]>,scrape:vi.fn(),fallback:vi.fn(),local:vi.fn()}));
vi.mock('@/lib/supabase/admin',()=>({createAdminClient:()=>({from(table:string){const filters:((r:any)=>boolean)[]=[];let update:any;const result=()=>{const rows=(state.tables[table] || []).filter(r=>filters.every(f=>f(r)));if(update)rows.forEach(r=>Object.assign(r,structuredClone(update)));return {data:structuredClone(rows),error:null};};const q:any={select:()=>q,eq:(k:string,v:any)=>{filters.push(r=>r[k]===v);return q;},gt:(k:string,v:number)=>{filters.push(r=>r[k]>v);return q;},in:(k:string,values:any[])=>{filters.push(r=>values.includes(r[k]));return q;},update:(v:any)=>{update=v;return q;},upsert:(v:any)=>{const rows=state.tables[table] ||= [];const key=table==='tracked_account_snapshots' ? 'observation_key' : table==='scout_comment_evidence' ? 'comment_key' : 'scout_session_id';const existing=rows.find(r=>r[key]===v[key]);existing ? Object.assign(existing,v) : rows.push({...v,id:v.id || `e${rows.length}`});return q;},order:()=>q,limit:()=>q,single:async()=>({...result(),data:result().data[0]}),then:(resolve:any)=>Promise.resolve(result()).then(resolve)};return q;}})}));
vi.mock('./providers',async()=>{const actual=await vi.importActual<any>('./providers');return {...actual,scrape:state.scrape,parseProfile:(r:any)=>r,parsePost:(r:any)=>r};});
vi.mock('@/lib/scraper/scraper-adapter',()=>({scrapeProfile:state.fallback}));
vi.mock('@/lib/sport-hub/channel-store',()=>({getStoredEntityChannels:state.local}));
import {syncEntity,executeExtendedSession,commentPreview} from './tasks';
import {ScoutError,PendingScout} from './providers';
const url='https://www.instagram.com/nike/';
beforeEach(()=>{state.scrape.mockReset();state.fallback.mockReset();state.local.mockReset();state.tables={tracked_accounts:[{id:'t',platform:'instagram',profile_url:url,followers_count:100,engagement_rate:2}],kols:[{id:'k',name:'Original Name',profile_url:url,followers:100,avg_views:50,er:2,user_locked_fields:['followers'],channels:[{url,isPrimary:true}]}],scouted_posts:[{id:'p',kol_id:'k',platform:'Instagram',comments:5,post_url:'https://www.instagram.com/p/a/'}],scout_budget_settings:[{session_usd:0.1,daily_usd:10,run_usd:0.25,enabled:true}],scout_comment_evidence:[],tracked_account_snapshots:[],kol_metric_snapshots:[]};});
describe('persistent observation workflows',()=>{
 it('uses the configured policy for the comment preview without starting a provider',async()=>{expect(await commentPreview('k')).toMatchObject({budgetCeilingUsd:0.1,maxComments:100});state.tables.scout_budget_settings[0].enabled=false;expect(await commentPreview('k')).toMatchObject({budgetCeilingUsd:0});expect(state.scrape).not.toHaveBeenCalled();});
 it('prefers persisted channels, respects locks, preserves missing metrics and writes valid zero',async()=>{
  state.local.mockReturnValue([{url:'https://www.facebook.com/stale',isPrimary:true}]);state.scrape.mockImplementation(async(_s,_p,task)=>task==='profile-details' ? [{url,followers:0,bio:'Original bio',posts:[],provenance:{runId:'r',fetchedAt:'2026-10-05T00:00:00Z'}}] : [{authorUrl:url,views:0,likes:null,comments:0}]);
  await syncEntity('s','k','kol');const saved=state.tables.kols[0];expect(state.local).not.toHaveBeenCalled();expect(state.scrape.mock.calls[0][1]).toBe('Instagram');expect(saved).toMatchObject({followers:100,avg_views:0,er:2,scout_missing_metrics:['er'],pending_scout_diff:{changes:{bio:{scouted:'Original bio'}}}});expect(state.tables.kol_metric_snapshots).toHaveLength(0);
 });
 it('skips an unsupported primary channel and uses the persisted supported profile URL',async()=>{state.tables.kols[0].channels=[{url:'https://www.youtube.com/@hana',isPrimary:true}];state.scrape.mockImplementation(async(_s,_p,task)=>task==='profile-details' ? [{url,followers:100,bio:'',posts:[]}] : []);await syncEntity('s','k','kol');expect(state.scrape.mock.calls[0][1]).toBe('Instagram');expect(state.scrape.mock.calls[0][3]).toBe('https://instagram.com/nike');});
 it('reuses the fallback observation on retry and deduplicates its snapshot',async()=>{
  state.scrape.mockRejectedValue(new ScoutError('Unavailable','ACCESS_UNAVAILABLE'));state.fallback.mockResolvedValue({username:'nike',displayName:'Nike',followersCount:0,recentPosts:[]});
  await syncEntity('s','t','tracked');await syncEntity('s','t','tracked');expect(state.fallback).toHaveBeenCalledTimes(1);expect(state.tables.tracked_account_snapshots).toHaveLength(1);expect(state.tables.tracked_accounts[0]).toMatchObject({followers_count:0,engagement_rate:2,scrape_metadata:{provenance:{source:'public-playwright'},missingMetrics:['er']}});
 });
 it('never repeats a failed fallback attempt within the same session',async()=>{
  state.scrape.mockRejectedValue(new ScoutError('Unavailable','ACCESS_UNAVAILABLE'));state.fallback.mockRejectedValue(new Error('Browser timeout'));await expect(syncEntity('s','t','tracked')).rejects.toThrow('Browser timeout');await expect(syncEntity('s','t','tracked')).rejects.toMatchObject({code:'FALLBACK_ALREADY_ATTEMPTED'});expect(state.fallback).toHaveBeenCalledTimes(1);expect(state.tables.tracked_accounts[0].followers_count).toBe(100);
 });
 it.each(['BUDGET_EXHAUSTED','BILLING_ERROR','APPROVAL_REQUIRED','SCHEMA_MISMATCH'])('does not fallback for %s',async code=>{state.scrape.mockRejectedValue(new ScoutError('Blocked',code));await expect(syncEntity('s','t','tracked')).rejects.toMatchObject({code});expect(state.fallback).not.toHaveBeenCalled();});
 it('fails an entirely unsuccessful comment collection rather than reporting success',async()=>{state.scrape.mockRejectedValue(new ScoutError('Budget exhausted','BUDGET_EXHAUSTED'));expect(await executeExtendedSession({id:'s',kind:'comments',params:{kolId:'k',selectedPostIds:['p']}})).toMatchObject({success:false,code:'BUDGET_EXHAUSTED',counts:{comments:0,failed:1}});});
 it('persists original comment text with evidence IDs, caps each post and preserves evidence IDs on retry',async()=>{state.scrape.mockResolvedValue(Array.from({length:25},(_,i)=>({id:String(i),text:`Bình luận ${i}`,_provenance:{runId:'r',fetchedAt:'2026-10-05T00:00:00Z'}})));const session={id:'s',kind:'comments',params:{kolId:'k',selectedPostIds:['p']}};await executeExtendedSession(session);const first=structuredClone(state.tables.scouted_posts[0].comments_sample);await executeExtendedSession(session);expect(state.tables.scout_comment_evidence).toHaveLength(20);expect(state.tables.scouted_posts[0].comments_sample).toEqual(first);expect(first[0].text).toBe('Bình luận 0');expect(first[0].id).toBeTruthy();});
 it('leaves pending comment runs resumable',async()=>{state.scrape.mockRejectedValue(new PendingScout());await expect(executeExtendedSession({id:'s',kind:'comments',params:{kolId:'k',selectedPostIds:['p']}})).rejects.toBeInstanceOf(PendingScout);});
});
